name: CI/CD for SimpleBlog Production

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        ports:
          - 5432:5432

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_blog_test

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/simple_blog_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

        with:
          ruby-version: 4.0.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rails test

      - name: Trigger Render deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
          ${{ secrets.RENDER_DEPLOY_HOOK_URL }}